server:
  port: 9080
  error:
    include-message: always
    include-stacktrace: always

logging:
  file:
    name: logs/${info.app.name}.log
  pattern:
    console: "%msg %n"
    file: "%d{HH:mm:ss} %-5level %logger{15} [%X{headers}] : %msg %n"
  level:
    root: INFO
    com.invex.jmc.employee: DEBUG
    org.hibernate.type.descriptor.sql: ERROR
    org.hibernate.stat: ERROR
    org.springdoc: ERROR
    org.springframework.web: ERROR
  headers:
  - uuid

springdoc:
  use-bean-validation: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/invex?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ENC(vxkihes8yoCAg+H3bEa++4fceb/ihWzhr5d9wqPZkYV+TewqzlRKFuKgWfOc+4GC)
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ${info.app.name}
  security:
    user:
      name: jorgeAdmin
      password: ENC(Uo5yOlC7DxUp7hb0WlP1E7xpWt7dseOxjzp5PWCyY3ijkKeHYok40655wPQz7OzX)
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always

  datasource.hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    max-lifetime: 1800000
    connection-timeout: 30000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://jorgeAdmin:eurekaJMC@localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"           # expone todos los endpoints
  endpoint:
    health:
      show-details: always

# Información personalizada para /actuator/info
info:
  app:
    name: ${info.app.name}
    version: 1.0.0

########## HEADERS Validación
headers:
  apis:
    -
      name: invex-employee
      required:
      - Accept
      - uuid